repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform.git
  rev: v1.74.1
  hooks:
    # - id: terraform_docs
    - id: terraform_fmt

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
    - id: tflint
    - id: shellcheck
    - id: gofmt
    - id: golint
