parameters:
- name: runDeploy
  type: boolean
- name: kubeformNs
  type: string
- name: kubeconfigBastion
  type: string
- name: kubeconfigWorkload
  type: string

stages:
- stage: Run_SSO_Onboarding
  jobs:
  - job: SSO_Onboard
    displayName: SSO_Onboard
    condition: eq('${{ parameters.runDeploy }}', true)
    steps:
    - task: DownloadSecureFile@1
      displayName: Download kubeconfig bastion
      name: kubeconfig_bastion
      inputs:
        secureFile: ${{ parameters.kubeconfigBastion }}
    - task: DownloadSecureFile@1
      displayName: Downlaod kubeconfig workload
      name: kubeconfig_wk
      inputs:
        secureFile: ${{ parameters.kubeconfigWorkload }}
    - script: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        kubectl port-forward -n tinyproxy deployment/de-bastion-proxy 8888:8888 --kubeconfig=$(kubeconfig_bastion.secureFilePath) &>/dev/null &
        sleep 5

        export HTTPS_PROXY=localhost:8888
        export KUBECONFIG=$(kubeconfig_wk.secureFilePath)
        kubectl create namespace ${{ parameters.kubeformNs }} --dry-run=client -o yaml | kubectl apply -f -
        unset HTTPS_PROXY
        unset KUBECONFIG
