name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env-class: ["npd","prd"]
    outputs:
      matrix-npd: ${{ steps.set-matrix.outputs.hello-npd }}
      matrix-prd: ${{ steps.set-matrix.outputs.hello-prd }}
    steps:
    - id: set-matrix
      run: echo "name=hello-${{ matrix.env-class }}" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    env:
      OUTPUT-NPD: ${{ needs.job1.outputs.matrix-npd }}
      OUTPUT-PRD: ${{ needs.job1.outputs.matrix-prd }}
    steps:
      - run: |
          echo "${OUTPUT-NPD}"
      - run: |
          echo "${OUTPUT-PRD}"
        #job2:
        #  needs: job1
        #  runs-on: ubuntu-latest
        #  strategy:
        #    matrix: ${{fromJson(needs.job1.outputs.matrix)}}
        #  steps:
        #  - run: echo ${{ matrix.project }}
        #  - run: echo ${{ matrix.config }}
