name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env-class: ["npd","prd"]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.job1.outputs.matrix }}
        #job2:
        #  needs: job1
        #  runs-on: ubuntu-latest
        #  strategy:
        #    matrix: ${{fromJson(needs.job1.outputs.matrix)}}
        #  steps:
        #  - run: echo ${{ matrix.project }}
        #  - run: echo ${{ matrix.config }}
