# This is a basic workflow to help you get started with Actions

name: Onboard

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "reusable-workflow" ]

permissions:
  contents: write
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  onboard-team:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: Checkout reusbale-workflow branch
        with:
          ref: reusable-workflow

      - uses: actions/checkout@v4
        name: Checkout onboard branch
        with:
          repository: amocha/gha
          path: onboard
          ref: onboard

      - name: test
        run: |
           pwd
           ls -l ../
           ls -l ../../

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Execute Onboarding
        run: python scripts/onboard.py
