# This is a basic workflow to help you get started with Actions

name: Onboard

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "reusable-workflow" ]
  schedule:
    - cron: '*/5 * * * *' 

permissions:
  contents: write
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  onboard-team:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: Checkout reusbale-workflow branch
        with:
          ref: reusable-workflow

      - uses: actions/checkout@v4
        name: Checkout onboard branch
        with:
          repository: amocha/gha
          path: onboard
          ref: onboard

      - name: Prepare onboarding list
        run: | 
             echo "Iterate through the teams yaml in teams folder and identify which teams are not onboarded or need to be reonboarded"
      
      - name: Run Onboarding
        run: | 
            echo "run onboarding  using  strategy matrix"

            #      # Runs a set of commands using the runners shell
            #      - name: Run a multi-line script
            #        run: |
            #           pwd
            #           ls
            #           ls */*
            #      - name: Commit report
            #        run: |
            #          echo "hello" > onboard.yaml
            #          git config user.name "dep_onboard@github.com"
            #          git config user.email "dep_onboard@noreply.github.com"
            #          git commit -am "Automated report"
            #          git push
            #        working-directory: onboard
