name: Test Reusable

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      genv:
        default: npd
        type: choice
        options:
          - npd
          - prd
jobs:
  test-secret:
    if: ${{ github.ref_name != 'main' }}
    uses: amocha/reusable-workflows/.github/workflows/testwrapper.yml@main
    with:
         genv: ${{ inputs.genv }}
    secrets: inherit
  test-2:
    runs-on: ubuntu-latest
    needs: test-secret
    steps:
      - run: echo ${{ needs.plan.outputs.firstword }}  
  test-secret1:
    if: ${{ needs.plan.result != 'success' }}
    uses: amocha/reusable-workflows/.github/workflows/testwrapper.yml@main
    with:
         genv: ${{ inputs.genv }}
    secrets: inherit
